foreground   #e7e5e7
background   #0b0907
cursor       #e7e5e7

color0       #0b0907
color8       #a1a0a1
color1       #876362
color9       #876362
color2       #817D84
color10      #817D84
color3       #938E93
color11      #938E93
color4       #AAA5AB
color12      #AAA5AB
color5       #C1BBBD
color13      #C1BBBD
color6       #D4D1D4
color14      #D4D1D4
color7       #e7e5e7
color15      #e7e5e7
