# Other settings
window_padding_width 10
font_family Hack Nerd Font
font_size 14.0

include /home/valenyqs/.config/kitty/colors-kitty.conf

# Cursor animations
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5
cursor_trail 3
cursor_trail_decay 0.1 0.4

# Paste with Ctrl+V
map ctrl+v paste_from_clipboard